---
- name: NPM | Adding chris-lea node PPA
  apt_repository: repo='ppa:chris-lea/node.js' state=present update_cache=yes

- name: NPM | Installing node.js and npm
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - nodejs

- name: NPM | Make sure npm is latest
  command: npm install -g npm

- name: NPM | Adding npm modules
  become: yes
  npm: name={{ item }} global=yes
  with_items:
    - bower
    - grunt-cli
    - jshint
    - ember-cli
