---
- name: Adding postgre apt
  become: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present

- name: Importing repo key
  become: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Installing postgreSQL 9.4
  become: yes
  apt: pkg={{ item }} update_cache=true
  with_items:
    - postgresql-9.4
    - postgresql-contrib
    - python-psycopg2

- name: Starting postgreSQL service and making sure it run on start
  service: name=postgresql state=started enabled=yes
  register: started
  tags: postgresql

- name: Waiting for postgre service...
  command: sleep 2
  when: started.changed
  tags: postgresql

- name: Create database featur
  postgresql_db: name=featur

- name: Set postgre user access to featur db
  postgresql_user: db=featur name=postgres password=p0stgr3s priv=ALL
