---
- name: PostgreSQL | Importing repo key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: PostgreSQL | Adding postgre apt
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present update_cache=yes

- name: PostgreSQL | Installing postgreSQL 9.4
  become: yes
  apt: pkg={{ item }} update_cache=true
  with_items:
    - postgresql-9.4
    - postgresql-contrib
    - python-psycopg2

- name: PostgreSQL | Start postgreSQL service and make sure it runs on start
  service: name=postgresql state=started enabled=yes
  register: started

- name: PostgreSQL | Waiting for postgre service...
  command: sleep 2
  when: started.changed
  tags: postgresql

- name: PostgreSQL | Create database {{ pg_db }}
  become: yes
  become_user: postgres
  postgresql_db: name={{ pg_db }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'

- name: PostgreSQL | Create dev postgre {{ pg_user }}
  become: yes
  become_user: postgres
  postgresql_user: name={{ pg_user }} password={{ pg_pass }} state=present role_attr_flags=CREATEDB,SUPERUSER

- name: PostgreSQL | Ensure user has access to database
  become: yes
  become_user: postgres
  postgresql_user: db={{ pg_db }} name={{ pg_user }} password={{ pg_pass }} priv=ALL
