# vagrant_config.yml
boxconfig:
  name: localdev.talent.jvm
  box: ubuntu/trusty64
  ram: 2048
  ip: 192.168.50.10
  aliases: ["api.mytravelapp.dev","mytravelapp.dev", "hotelsapi.dev"]

postgresql:
  user: vagrant
  userpass: vagrant
  dbname: hotels

sync_folders:
    path: /Users/clopez/projects/talent/booking-app
    mount: /home/vagrant/projects/
